# fly.toml app configuration file generated for haidara-string-analyzer on 2025-10-20T22:08:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'haidara-string-analyzer'
primary_region = 'jnb'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    method = 'get'
    path = '/test'

  [[http_service.checks]]
    interval = '1m0s'
    timeout = '10s'
    method = 'get'
    path = '/test/db'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
