server:
  port: ${PORT:8080}
  
spring:
  application:
    name: string-analyzer
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mvc:
    problemdetails:
      enabled: true

logging:
  level:
    com.haidara.stringanalyzer: INFO
  pattern:
    level: "%5p"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always
