server:
  port: ${PORT:8080}
  
spring:
  application:
    name: string-analyzer
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat

logging:
  level:
    com.haidara.stringanalyzer: INFO
    org.springframework.web: INFO
  pattern:
    level: "%5p"
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always
